package Interfaces;

import Agents.HospitalInfoSource;
import Classes.Doctor;
import Classes.Specialty;
import jade.gui.GuiEvent;
import java.util.TreeMap;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class AddDoctorMenu extends javax.swing.JFrame {
    
    private static final int ADD_DOCTOR = 105;
    
    private HospitalInfoSource source;
    private TreeMap<Integer, Doctor> doctors;

    public AddDoctorMenu() {
        initComponents();
    }
    
    public AddDoctorMenu(HospitalInfoSource source, TreeMap<Integer, Doctor> doctors) {
        initComponents();
        this.source = source;
        this.doctors = doctors;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NameLabel = new javax.swing.JLabel();
        SpecialtyTypeLabel = new javax.swing.JLabel();
        SpecialtyNameLabel = new javax.swing.JLabel();
        AddDoctorButton = new javax.swing.JButton();
        CancelButton = new javax.swing.JButton();
        NameText = new javax.swing.JTextField();
        SpecialtyTypeComboBox = new javax.swing.JComboBox<>();
        SpecialtyNameComboBox = new javax.swing.JComboBox<>();
        HoursLabel = new javax.swing.JLabel();
        HoursComboBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        NameLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        NameLabel.setText("Nome");
        NameLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        SpecialtyTypeLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        SpecialtyTypeLabel.setText("Especialidade");
        SpecialtyTypeLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        SpecialtyNameLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        SpecialtyNameLabel.setText("Foco");
        SpecialtyNameLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        AddDoctorButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        AddDoctorButton.setText("Adicionar Médico");
        AddDoctorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddDoctorButtonActionPerformed(evt);
            }
        });

        CancelButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CancelButton.setText("Cancelar");
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });

        SpecialtyTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cirurgia", "Exame", "Transplante" }));

        SpecialtyNameComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cabeça", "Coração", "Perna", "Estômago", "Rim" }));

        HoursLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        HoursLabel.setText("Horário");
        HoursLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        HoursComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00:00h-08:00h", "08:00h-16:00h", "16:00h-00:00h" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(NameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(SpecialtyTypeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(SpecialtyNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(HoursLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(NameText)
                            .addComponent(SpecialtyTypeComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(SpecialtyNameComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(HoursComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(AddDoctorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(CancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(NameText)
                    .addComponent(NameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SpecialtyTypeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SpecialtyTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SpecialtyNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SpecialtyNameComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(HoursComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HoursLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddDoctorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed
        EditDoctorMenu editDoctorMenu = new EditDoctorMenu(source, doctors);
        editDoctorMenu.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        editDoctorMenu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_CancelButtonActionPerformed

    private void AddDoctorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddDoctorButtonActionPerformed
        if(!NameText.getText().isEmpty()) {
            String name = NameText.getText();
            String specialtyType = SpecialtyTypeComboBox.getSelectedItem().toString();
            String specialtyName = SpecialtyNameComboBox.getSelectedItem().toString();
            String hour = HoursComboBox.getSelectedItem().toString();
            
            Specialty s = new Specialty(specialtyType, specialtyName);
            Doctor d = new Doctor(s, name);
            d.fillAvailableDays(hour);
            
            GuiEvent ge = new GuiEvent(d, ADD_DOCTOR);
            source.postGuiEvent(ge);
            
            EditDoctorMenu editDoctorMenu = new EditDoctorMenu(source, doctors);
            editDoctorMenu.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
            editDoctorMenu.setVisible(true);
            
            this.dispose();
        }
        else JOptionPane.showMessageDialog(this, "Existem campos por preencher!", "Adicionar Médico", JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_AddDoctorButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddDoctorMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddDoctorMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddDoctorMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddDoctorMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddDoctorMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddDoctorButton;
    private javax.swing.JButton CancelButton;
    private javax.swing.JComboBox<String> HoursComboBox;
    private javax.swing.JLabel HoursLabel;
    private javax.swing.JLabel NameLabel;
    private javax.swing.JTextField NameText;
    private javax.swing.JComboBox<String> SpecialtyNameComboBox;
    private javax.swing.JLabel SpecialtyNameLabel;
    private javax.swing.JComboBox<String> SpecialtyTypeComboBox;
    private javax.swing.JLabel SpecialtyTypeLabel;
    // End of variables declaration//GEN-END:variables
}
