package Interfaces;

import Agents.HospitalManager;
import Classes.Patient;
import Classes.Specialty;
import jade.gui.GuiEvent;
import javax.swing.JOptionPane;

public class AddPatientMenu extends javax.swing.JFrame {
    
    private static final int ADD_PATIENT = 101;
    
    private HospitalManager manager;

    public AddPatientMenu() {
        initComponents();
    }
    
    public AddPatientMenu(HospitalManager manager) {
        initComponents();
        this.manager = manager;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NameLabel = new javax.swing.JLabel();
        AgeLabel = new javax.swing.JLabel();
        UrgencyDegreeLabel = new javax.swing.JLabel();
        SpecialtyTypeLabel = new javax.swing.JLabel();
        SpecialtyNameLabel = new javax.swing.JLabel();
        AddPatientButton = new javax.swing.JButton();
        CancelButton = new javax.swing.JButton();
        NameText = new javax.swing.JTextField();
        AgeText = new javax.swing.JTextField();
        SpecialtyTypeComboBox = new javax.swing.JComboBox<>();
        SpecialtyNameComboBox = new javax.swing.JComboBox<>();
        UrgencyDegreeNavigator = new javax.swing.JSlider();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        NameLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        NameLabel.setText("Nome");
        NameLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        AgeLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        AgeLabel.setText("Idade");
        AgeLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        UrgencyDegreeLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        UrgencyDegreeLabel.setText("Grau de Urgência");
        UrgencyDegreeLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        SpecialtyTypeLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        SpecialtyTypeLabel.setText("Tipo de Marcação");
        SpecialtyTypeLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        SpecialtyNameLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        SpecialtyNameLabel.setText("Foco da Marcação");
        SpecialtyNameLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        AddPatientButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        AddPatientButton.setText("Adicionar Paciente");
        AddPatientButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddPatientButtonActionPerformed(evt);
            }
        });

        CancelButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CancelButton.setText("Cancelar");
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });

        SpecialtyTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cirurgia", "Exame", "Transplante" }));

        SpecialtyNameComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cabeça", "Coração", "Perna", "Estômago", "Rim" }));

        UrgencyDegreeNavigator.setMaximum(5);
        UrgencyDegreeNavigator.setMinimum(1);
        UrgencyDegreeNavigator.setValue(1);
        UrgencyDegreeNavigator.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(UrgencyDegreeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(AgeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(NameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(SpecialtyTypeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                            .addComponent(SpecialtyNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(NameText)
                            .addComponent(AgeText, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE)
                            .addComponent(SpecialtyTypeComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(SpecialtyNameComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(UrgencyDegreeNavigator, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(AddPatientButton, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(104, 104, 104)
                        .addComponent(CancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(NameText)
                    .addComponent(NameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(AgeText)
                        .addGap(8, 8, 8))
                    .addComponent(AgeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SpecialtyTypeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SpecialtyTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SpecialtyNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SpecialtyNameComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(UrgencyDegreeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UrgencyDegreeNavigator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddPatientButton, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_CancelButtonActionPerformed

    private void AddPatientButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddPatientButtonActionPerformed
        if(!NameText.getText().isEmpty() && !AgeText.getText().isEmpty()) {
            try {
                String name = NameText.getText();
                int age = Integer.parseInt(AgeText.getText());
                String specialtyType = SpecialtyTypeComboBox.getSelectedItem().toString();
                String specialtyName = SpecialtyNameComboBox.getSelectedItem().toString();
                int urgencyDegree = UrgencyDegreeNavigator.getValue();
            
                Specialty s = new Specialty(specialtyType, specialtyName);
                Patient p = new Patient(s, name, age, urgencyDegree);
            
                GuiEvent ge = new GuiEvent(p, ADD_PATIENT);
                manager.postGuiEvent(ge);
            
                this.dispose();
            } catch(NumberFormatException ex) {
                JOptionPane.showMessageDialog(this, "Idade inválida!", "Adicionar Paciente", JOptionPane.PLAIN_MESSAGE);
            }
        }
        else JOptionPane.showMessageDialog(this, "Existem campos por preencher!", "Adicionar Paciente", JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_AddPatientButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddPatientMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddPatientMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddPatientMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddPatientMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddPatientMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddPatientButton;
    private javax.swing.JLabel AgeLabel;
    private javax.swing.JTextField AgeText;
    private javax.swing.JButton CancelButton;
    private javax.swing.JLabel NameLabel;
    private javax.swing.JTextField NameText;
    private javax.swing.JComboBox<String> SpecialtyNameComboBox;
    private javax.swing.JLabel SpecialtyNameLabel;
    private javax.swing.JComboBox<String> SpecialtyTypeComboBox;
    private javax.swing.JLabel SpecialtyTypeLabel;
    private javax.swing.JLabel UrgencyDegreeLabel;
    private javax.swing.JSlider UrgencyDegreeNavigator;
    // End of variables declaration//GEN-END:variables
}
