package Interfaces;

import Agents.HospitalInfoSource;
import Classes.Day;
import Classes.Doctor;
import jade.gui.GuiEvent;
import java.util.TreeMap;
import javafx.util.Pair;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class EditDoctorMenu extends javax.swing.JFrame {
    
    private static final int REMOVE_DAY = 106;
    private static final int REMOVE_DOCTOR = 107;
    
    private HospitalInfoSource source;
    private TreeMap<Integer, Doctor> doctors;

    public EditDoctorMenu() {
        initComponents();
    }
    
    public EditDoctorMenu(HospitalInfoSource source, TreeMap<Integer, Doctor> doctors) {
        initComponents();
        
        this.source = source;
        this.doctors = doctors;
        
        for(Doctor d : doctors.values()) DoctorListComboBox.addItem(d.getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DoctorListLabel = new javax.swing.JLabel();
        AvailableDaysLabel = new javax.swing.JLabel();
        AvailableDaysButton = new javax.swing.JButton();
        AddDoctorButton = new javax.swing.JButton();
        RemoveDayButton = new javax.swing.JButton();
        GoBackButton = new javax.swing.JButton();
        DoctorListComboBox = new javax.swing.JComboBox<>();
        AvailableDaysComboBox = new javax.swing.JComboBox<>();
        RemoveDoctorButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        DoctorListLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        DoctorListLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DoctorListLabel.setText("Lista de Médicos");

        AvailableDaysLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        AvailableDaysLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AvailableDaysLabel.setText("Dias Disponíveis");

        AvailableDaysButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        AvailableDaysButton.setText("Dias Disponíveis");
        AvailableDaysButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AvailableDaysButtonActionPerformed(evt);
            }
        });

        AddDoctorButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        AddDoctorButton.setText("Adicionar Médico");
        AddDoctorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddDoctorButtonActionPerformed(evt);
            }
        });

        RemoveDayButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        RemoveDayButton.setText("Remover Dia");
        RemoveDayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveDayButtonActionPerformed(evt);
            }
        });

        GoBackButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        GoBackButton.setText("Retroceder");
        GoBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GoBackButtonActionPerformed(evt);
            }
        });

        RemoveDoctorButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        RemoveDoctorButton.setText("Remover Médico");
        RemoveDoctorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveDoctorButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AddDoctorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RemoveDoctorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(132, 132, 132)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RemoveDayButton, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AvailableDaysButton, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 117, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(DoctorListLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                            .addComponent(DoctorListComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(AvailableDaysLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                            .addComponent(AvailableDaysComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(249, 249, 249)
                .addComponent(GoBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(AvailableDaysLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(AvailableDaysComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(DoctorListLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(DoctorListComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AddDoctorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AvailableDaysButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RemoveDayButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RemoveDoctorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(GoBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AvailableDaysButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AvailableDaysButtonActionPerformed
        AvailableDaysComboBox.removeAllItems();
        String name = (String)DoctorListComboBox.getSelectedItem();
        if(name != null) {
            for(Doctor d : doctors.values()) {
                if(d.getName().equals(name)) {
                    for(Day day : d.getAvailableDays().values()) AvailableDaysComboBox.addItem("" + day.getDay());
                    break;
                }
            }
        }
        else JOptionPane.showMessageDialog(this, "Não há médicos selecionados!", "Dias Disponíveis", JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_AvailableDaysButtonActionPerformed

    private void AddDoctorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddDoctorButtonActionPerformed
        AddDoctorMenu addDoctorMenu = new AddDoctorMenu(source, doctors);
        addDoctorMenu.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        addDoctorMenu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_AddDoctorButtonActionPerformed

    private void GoBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GoBackButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_GoBackButtonActionPerformed

    private void RemoveDayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveDayButtonActionPerformed
        String name = (String)AvailableDaysComboBox.getSelectedItem();
        if(name != null) {
            int day = Integer.parseInt(name);
            String doctor = (String)DoctorListComboBox.getSelectedItem();
            
            Pair<String, Integer> pair = new Pair(doctor, day);
            GuiEvent ge = new GuiEvent(pair, REMOVE_DAY);
            source.postGuiEvent(ge);
            
            this.dispose();
        }
        else JOptionPane.showMessageDialog(this, "Não há dias selecionados!", "Remover Dia", JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_RemoveDayButtonActionPerformed

    private void RemoveDoctorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveDoctorButtonActionPerformed
        String name = (String)DoctorListComboBox.getSelectedItem();
        if(name != null) {
            GuiEvent ge = new GuiEvent(name, REMOVE_DOCTOR);
            source.postGuiEvent(ge);
            this.dispose();
        }
        else JOptionPane.showMessageDialog(this, "Não há médicos selecionados!", "Remover Médico", JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_RemoveDoctorButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditDoctorMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditDoctorMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditDoctorMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditDoctorMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditDoctorMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddDoctorButton;
    private javax.swing.JButton AvailableDaysButton;
    private javax.swing.JComboBox<String> AvailableDaysComboBox;
    private javax.swing.JLabel AvailableDaysLabel;
    private javax.swing.JComboBox<String> DoctorListComboBox;
    private javax.swing.JLabel DoctorListLabel;
    private javax.swing.JButton GoBackButton;
    private javax.swing.JButton RemoveDayButton;
    private javax.swing.JButton RemoveDoctorButton;
    // End of variables declaration//GEN-END:variables
}
